(()=>{
const c=document.getElementById('net'),ctx=c?.getContext('2d'),reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
if(!c||!ctx)return;
let W=0,H=0,D=1,last=performance.now(),pts=[],farPts=[],links=[],signals=[],mx=0,my=0,tx=0,ty=0,suspended=false;
const R=(a,b)=>a+Math.random()*(b-a),N=n=>Math.floor(R(0,n));
function makePoint(far=false){return{x:R(-60,W+60),y:R(20,H+50),vx:R(-.007,.007)*(far?.7:1),vy:R(-.005,.005)*(far?.7:1),r:R(far?.2:.45,far?.7:1.15),p:R(0,6.28),a:R(far?.08:.18,far?.2:.52),z:R(.35,far?.72:.95)}}
function resize(){D=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;c.width=W*D;c.height=H*D;ctx.setTransform(D,0,0,D,0,0);const mobile=W<700;const count=Math.max(mobile?32:42,Math.min(mobile?52:78,Math.floor(W*H/(mobile?24000:19000))));pts=Array.from({length:count},()=>makePoint());farPts=Array.from({length:Math.max(mobile?12:22,Math.floor(W*H/(mobile?52000:36000)))},()=>makePoint(true));links=Array.from({length:Math.max(mobile?9:14,Math.floor(W/(mobile?110:82)))},()=>({a:N(count),b:N(count),p:R(0,1),v:R(.00012,.00028)}));signals=Array.from({length:mobile?3:5},()=>({a:N(count),b:N(count),p:R(0,1),v:R(.00008,.00019),delay:R(0,9000)}))}
function hubPoint(){const hub=document.querySelector('.hub');if(!hub)return{x:W/2,y:H*.43};const r=hub.getBoundingClientRect();return{x:r.left+r.width/2,y:r.top+r.height/2}}
function cards(){return[...document.querySelectorAll('.card')].map(card=>{const r=card.getBoundingClientRect();return{x:r.left+r.width/2,y:r.top}})}
function node(p,t,ox=0,oy=0){const a=p.a*(.7+.3*(.5+.5*Math.sin(t*.00055+p.p)));ctx.fillStyle=`rgba(157,174,119,${a})`;ctx.fillRect(p.x+ox,p.y+oy,p.r,p.r)}
function line(a,b,alpha=.025){ctx.strokeStyle=`rgba(119,137,97,${alpha})`;ctx.lineWidth=1;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}
function atmosphere(t,hp){const px=reduce?0:tx*4,py=reduce?0:ty*4;const g=ctx.createRadialGradient(hp.x+px,hp.y+py,10,hp.x+px,hp.y+py,Math.max(W,H)*.62);g.addColorStop(0,'rgba(113,135,80,.065)');g.addColorStop(.3,'rgba(78,96,58,.03)');g.addColorStop(.7,'rgba(52,67,43,.01)');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}
function field(t,hp){
 const spacing=Math.max(60,W/18),phase=reduce?0:(t*.0015)%spacing;
 ctx.strokeStyle='rgba(121,143,88,.025)';ctx.lineWidth=1;ctx.lineCap='round';
 for(let gx=-W;gx<W*2;gx+=spacing){const skew=(gx-W*.5)*.16;ctx.beginPath();ctx.moveTo(gx+phase,0);ctx.lineTo(gx+phase+skew,H);ctx.stroke()}
 for(let i=0;i<6;i++){const y=hp.y-70+i*i*11+i*24;ctx.strokeStyle=`rgba(125,146,92,${.014+i*.003})`;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}
 if(!reduce){for(let i=0;i<5;i++){const a=t*.00005*(i%2?-1:1)+i*1.13,rad=Math.min(W,H)*.31,ox=hp.x+Math.cos(a)*rad,oy=hp.y+Math.sin(a)*rad*.62;ctx.fillStyle='rgba(188,205,150,.22)';ctx.fillRect(ox-1,oy-1,3,3)}}
}
function particles(t){const dt=Math.min(33,t-last);for(const p of farPts){if(!reduce){p.x+=p.vx*dt;p.y+=p.vy*dt}if(p.x<-60)p.x=W+60;if(p.x>W+60)p.x=-60;if(p.y<10)p.y=H+35;if(p.y>H+45)p.y=10;node(p,t,reduce?0:tx*6*(1-p.z),reduce?0:ty*4*(1-p.z))}for(let i=0;i<pts.length;i++)for(let j=i+1;j<pts.length;j++){const a=pts[i],b=pts[j],d=Math.hypot(a.x-b.x,a.y-b.y);if(d<105&&((i*17+j*7+Math.floor(t/6500))%53===0))line(a,b,.012+.028*(1-d/105))}for(const p of pts){if(!reduce){p.x+=p.vx*dt;p.y+=p.vy*dt}if(p.x<-50)p.x=W+50;if(p.x>W+50)p.x=-50;if(p.y<20)p.y=H+30;if(p.y>H+40)p.y=20;node(p,t,reduce?0:tx*12*(1-p.z),reduce?0:ty*8*(1-p.z))}}
function packets(t){const dt=Math.min(33,t-last);for(const q of links){const a=pts[q.a],b=pts[q.b];if(!a||!b)continue;if(!reduce)q.p=(q.p+q.v*dt)%1;const xx=a.x+(b.x-a.x)*q.p,yy=a.y+(b.y-a.y)*q.p;ctx.fillStyle='rgba(178,190,143,.28)';ctx.fillRect(xx,yy,2,2)}for(const s of signals){if(s.delay>0){if(!reduce)s.delay-=dt;continue}const a=pts[s.a],b=pts[s.b];if(!a||!b)continue;if(!reduce)s.p=(s.p+s.v*dt)%1;const xx=a.x+(b.x-a.x)*s.p,yy=a.y+(b.y-a.y)*s.p;ctx.fillStyle='rgba(188,201,150,.55)';ctx.fillRect(xx,yy,2.5,2.5);if(!reduce&&s.p>.995){s.a=N(pts.length);s.b=N(pts.length);s.p=0;s.delay=R(2200,9000)}}}
function routes(t,hp,items){if(!items.length)return;const spread=Math.min(W*.18,360);items.forEach((card,i)=>{const k=(i-(items.length-1)/2)/Math.max(1,(items.length-1)/2),sx=hp.x+k*spread,sy=hp.y,progress=reduce?1:Math.min(1,Math.max(0,(t-start-180-i*120)/700));if(progress<=0)return;const ex=card.x,ey=card.y;ctx.strokeStyle=`rgba(112,132,86,${.018+.032*progress})`;ctx.lineWidth=1.5;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(sx,sy);ctx.lineTo(sx+(ex-sx)*progress,sy+(ey-sy)*progress);ctx.stroke();if(!reduce){const p=(t*.00024+i*.021)%1,px=sx+(ex-sx)*Math.min(progress,p),py=sy+(ey-sy)*Math.min(progress,p);ctx.fillStyle='rgba(198,208,165,.68)';ctx.beginPath();ctx.arc(px,py,1.2,0,Math.PI*2);ctx.fill()}})}
let start=performance.now();
function frame(t){if(suspended){setTimeout(()=>frame(performance.now()),250);return}if(!reduce&&t-last<30){requestAnimationFrame(frame);return}ctx.fillStyle='#050706';ctx.fillRect(0,0,W,H);const hp=hubPoint(),items=cards();if(!reduce){tx+=(mx-tx)*.018;ty+=(my-ty)*.018}atmosphere(t,hp);field(t,hp);particles(t);packets(t);routes(t,hp,items);last=t;if(!reduce)requestAnimationFrame(frame)}
addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{suspended=document.hidden;if(!suspended)requestAnimationFrame(frame)});if(!reduce)addEventListener('pointermove',e=>{mx=e.clientX/W-.5;my=e.clientY/H-.5},{passive:true});resize();frame(performance.now());
})();